{% set name = "lalframe" %}
{% set version = "1.4.3" %}
{% set sha256 = "cbb6ed39abb5a02d792523fc53208330cf8adf02bc4290cac635d42577acb5b1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: http://software.ligo.org/lscsoft/source/lalsuite/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - pkg-config
    - make
    - {{ compiler('c') }}
    - swig>=3.0.7
  host:
    - gsl
    - libframe
    - lal
    - python
    - numpy
    - python-lal

test:
  imports:
    - lalframe
    - lalframe.frread
  commands:
    - lalframe_version --verbose
    - lalfr-vis --help

outputs:
  - name: lalframe
    requirements:
      build:
        - {{ compiler('c') }}
      host:
        - gsl
        - libframe
        - lal
      run:
        - gsl
        - libframe
        - lal
    files:
      - bin/lalfr-*
      - bin/lalframe_version
      - etc/lalframe-user-env.*
      - include/lal/Aggregation.h
      - include/lal/FrameCalibration.h
      - include/lal/LALFr*.h
      - lib/liblalframe*
      - lib/pkgconfig/lalframe*.pc
      - share/man/man1/lalfr-*
    test:
      commands:
        - lalframe_version --verbose
        - lalfr-vis --help
    about:
      home: https://wiki.ligo.org/DASWG/LALSuite
      license: GPLv3
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Frame Library
      description: |
        The LSC Algorithm Frame Library for gravitational wave data analysis.
        This package contains the shared-object libraries needed to run
        applications that use the LAL Frame library.
  - name: python-lalframe
    requirements:
      build:
        - {{ compiler('c') }}
        - swig>=3.0.7
      host:
        - {{ pin_subpackage('lalframe', exact=True) }}
        - python
        - numpy
      run:
        - {{ pin_subpackage('lalframe', exact=True) }}
        - python
        - numpy
        - python-lal
    files:
      - lib/python*/site-packages/lalframe/**
    test:
      imports:
        - lalframe
        - lalframe.frread
    about:
      home: https://wiki.ligo.org/DASWG/LALSuite
      license: GPLv3
      license_family: GPL
      license_file: COPYING
      summary: LSC Algorithm Frame Library
      description: |
        The LSC Algorithm Frame Library for gravitational wave data analysis.
        This package contains the python bindings.

about:
  home: https://wiki.ligo.org/DASWG/LALSuite
  license: GPLv3
  license_family: GPL
  summary: LSC Algorithm Frame Library

extra:
  recipe-maintainers:
    - duncanmmacleod
    - skymoo
