travis:
  secure:
    BINSTAR_TOKEN: pCkylNHubTSzLstnQzNlRkY6tHxs2YzblfjRiEqtpg5kBCLtZ2EE3Modhaov/Z1Won5HyLnG2OBspOncIfWT6cGIoN3mvwR7rHwRBQ23AYQUiujtr7khcDYxiMyznPMPCBp4PHmmNN1/SstyeS+6Ha4rGZDtQJuZgn27Ii4hD0sUVHmjddN1xc5DyWE6C2C0wvEbMpikOILzm3y/cqqvEjFunTolZmVnl25B0gdt80M417OV5mS06sqCmN3T4WPZ1yQ8LuYtyh8HUNYy2N9d3smtAAapcZgMtlkVTdn33VcLaIk045t+xn9TO04sDn9WVZW5otgmQa8eUrVh3TteWybZ+PMbVb5yV71R4Cnh6b4EbVMZnuSwqJp1iRAHlPABa8NNSZ3zNSDGOhW2Sy8R5rmI7q7uQzWMckCGYpwm5ThFO9BqrrBWgWqgVPI36Kb31serPgy8o2ShrWX9l/68Wpx8G8wtOlV00Cz67bLLuXYtGOukubmyWGGZeYoROvVM5AObmY5A3/9bfTKgDQiIioMqrcJ7P0LNBL0ZuUEE1U13my3RjxoG/JmzYCy+QvuAgnUBoydlQscEJ+6qKl68E6H1QYPzlkHEw6CVZJ7KfnQRSOYe/ZulytKc5B19TYRVKlw2o6vsIKLqdIh4U1tjiMFJcY/Fn5PshqDLwOdKTJE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
